<a href="https://colab.research.google.com/github/apotato369550/first-tensorflow-program/blob/main/first_tensor_program_learn_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# First TensorFlow Program


## Importing TensorFlow

In [ ]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Basic TensorFlow Variables

In [ ]:
text = tf.Variable("Yo", tf.string)
number = tf.Variable(35, tf.int16)
decimal = tf.Variable(4.4, tf.float64)

print(text)
print(number)
print(decimal)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'Yo'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=35>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=4.4>




## TensorFlow Ranks


In [ ]:
rank_1_tensor = tf.Variable(["This is a rank 1 tensor"], tf.string)
rank_2_tensor = tf.Variable([["This is a rank 2 tensor", "The shape of this tensor is 3", "I like cheeseburgers"], ["Yep, rank 2 fam", "Tensors must have a uniform amount of elements in each array", "bees"]], tf.string)

#display tensor ranks
print(tf.rank(rank_1_tensor))
print(tf.rank(rank_2_tensor))

print(rank_2_tensor.shape)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
(2, 3)



## Changing Tensor Shapes




In [ ]:
# tensor_1 contains populates the lists with 1s. It creates 1 list containing of 
# 2 other lists, each other list holding 3 elements
# [1, 2 ,3]
# [[1, 1, 1],[1, 1, 1]]
tensor_1 = tf.ones([1, 2, 3])

# tensor_2 is a reshaped version of tensor_1. Instead, it has 2 lists containing 
# 3 other lists, each other list only holding 1 element
# [2, 3, 1]
# [[1], [1], [1]], [[1], [1], [1]]
tensor_2 = tf.reshape(tensor_1, [2, 3, 1])

# the third tensor, tensor #3, is a reshaped version of tensor_2. It contains 3 
# lists.The -1 indicates that the machine will calculate the size of the 
# dimension in its place. This will in turn reshape the sensor into 3 lists, 
# each list containing 2 elements
# [3, 2]
# [1, 1], [1, 1], [1, 1]
tensor_3 = tf.reshape(tensor_2, [3, -1])

# parameters for tf.reshape()
# tf.reshape(<tensor>, <shape>)
# !!! the number of elements in the tensor needs to be equal to the product of
# all the elements in the shape
# tensor_elements = product_of_shape
# 6 elements = [1, 2, 3]
# 6 = 1 * 2 * 3
# 6 = 6

print(tensor_1)
print(tensor_2)
print(tensor_3)


tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Tensor Variable Types

In [ ]:
# There are four types of tensors
# Variables - Their value can be changed
# Constant, Placeholder, SparseTensor - Their values are immutable

## Slicing Tensors


In [ ]:
matrix = [[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          [13, 14, 15, 16]]

bigger_matrix = [[1, 2, 3, 4, 5, 6],
                 [7, 8, 9, 10, 11, 12],
                 [13, 14, 15, 16, 17, 18],
                 [19, 20, 21, 22, 23, 24],
                 [25, 26, 27, 28, 29, 30],
                 [31, 32, 33, 34, 35, 36]]

matrix_tensor = tf.Variable(matrix, tf.int32)
bigger_matrix_tensor = tf.Variable(bigger_matrix, tf.int32)

three = matrix_tensor[0, 2]

row_1 = matrix_tensor[0]

column_1 = matrix_tensor[:, 0]

# select every second row [2] starting from row 2 [1] = [1::2]
rows_2_and_4 = matrix_tensor[1::2]
rows_1_3_and_5 = bigger_matrix_tensor[0::2]

column_1_in_row_2_and_3 = matrix_tensor[1:3, 0]

print(three)
print(row_1)
print(column_1)
print(rows_2_and_4)
print(rows_1_3_and_5)
print(column_1_in_row_2_and_3)


tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([ 1  5  9 13], shape=(4,), dtype=int32)
tf.Tensor(
[[ 5  6  7  8]
 [13 14 15 16]], shape=(2, 4), dtype=int32)
tf.Tensor(
[[ 1  2  3  4  5  6]
 [13 14 15 16 17 18]
 [25 26 27 28 29 30]], shape=(3, 6), dtype=int32)
tf.Tensor([5 9], shape=(2,), dtype=int32)
